# To run the application with supabase, use the following command:
# Need to replace the environment variables (supabase and db related) with real values
# docker-compose up --build
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    environment:
      - ENVIRONMENT=DOCKER
      - PORT=3008
      - LOG_LEVEL=debug
      - GENERAL_RATE_LIMIT=100
      - AUTH_ENDPOINTS_RATE_LIMIT=10

      - DB_HOST=aws-0-ap-south-1.pooler.supabase.com #enter-supabase-db-host
      - DB_PORT=6543 #enter-supabase-db-port
      - DB_USER=postgres.yywpwcvjpvtkwknzjkkc #enter-supabase-db-user
      - DB_PASSWORD=aqqazaaq123 #enter-supabase-db-password
      - DB_NAME=postgres #enter-supabase-db-name
      - DB_SSLMODE=require #enter-supabase-db-sslmode

      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest

      - SUPABASE_URL= #enter_your_supabase_url
      - SUPABASE_KEY= #enter_your_supabase_key
      - SUPABASE_BUCKET= #enter_your_supabase_bucket
      - SUPABASE_JWT_SECRET_KEY= #enter_your_supabase_jwt_secret_key
      - SUPABASE_PROJECT_REFERENCE= #enter_your_supabase_project_reference

      - KEYWORDS=error,timeout,failure,unauthorized
      - DEV_SIMULATE_LOG_PROCESSING_LAG_MS=1000

    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3008/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - logflow-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - logflow-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

volumes:
  rabbitmq_data:

networks:
  logflow-network:
    driver: bridge 